# Generated by Django 5.2 on 2025-05-23 03:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('campaign_id', models.CharField(max_length=255, null=True)),
                ('tipo_presupuesto', models.CharField(choices=[('PRESUPUESTO_DIARIO', 'Presupuesto Diario'), ('PRESUPUESTO_TOTAL', 'Presupuesto Total')], max_length=20, null=True)),
                ('monto_presupuesto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('evento_cobro', models.CharField(choices=[('IMPRESIONES', 'Impresiones'), ('CLICS', 'Clics'), ('CLICS_EN_ENLACES', 'Clics en Enlaces'), ('VISTAS_DE_VIDEO', 'Vistas de Video')], max_length=20, null=True)),
                ('objetivos', models.CharField(choices=[('CLICS_EN_ENLACES', 'Clics en Enlaces'), ('ALCANCE', 'Alcance'), ('IMPRESIONES', 'Impresiones'), ('VISTAS_DE_VIDEO', 'Vistas de Video'), ('INTERACCION_CON_PUBLICACIONES', 'Interacción con Publicaciones')], max_length=50, null=True)),
                ('edad_min', models.IntegerField(null=True)),
                ('edad_max', models.IntegerField(null=True)),
                ('genero', models.CharField(choices=[('TODOS', 'Todos'), ('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=10, null=True)),
                ('ubicaciones', models.TextField(null=True)),
                ('intereses', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada')], default='PAUSED', max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField(default=datetime.date.today, null=True)),
                ('fecha_fin', models.DateField(default=datetime.date.today, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña Facebook',
                'verbose_name_plural': 'Campañas Facebook',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CampanaGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('tipo_campana', models.CharField(choices=[('SEARCH', 'Búsqueda'), ('DISPLAY', 'Display'), ('VIDEO', 'Video'), ('SHOPPING', 'Shopping')], max_length=20, null=True)),
                ('presupuesto_diario', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada')], default='PAUSADA', max_length=10, null=True)),
                ('palabras_clave', models.TextField(help_text='Palabras clave separadas por comas', null=True)),
                ('ubicaciones', models.TextField(help_text='Ubicaciones objetivo separadas por comas', null=True)),
                ('idiomas', models.TextField(help_text='Idiomas objetivo separados por comas', null=True)),
                ('puja_maxima', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('estrategia_puja', models.CharField(choices=[('MANUAL_CPC', 'CPC Manual'), ('MAXIMIZE_CONVERSIONS', 'Maximizar Conversiones'), ('TARGET_CPA', 'CPA Objetivo'), ('TARGET_ROAS', 'ROAS Objetivo')], max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña Google',
                'verbose_name_plural': 'Campañas Google',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CampanaInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('objetivo', models.CharField(max_length=100, null=True)),
                ('tipo_contenido', models.CharField(choices=[('historia', 'Historia'), ('post', 'Post'), ('reels', 'Reels'), ('carousel', 'Carousel')], max_length=50, null=True)),
                ('formato_anuncio', models.CharField(max_length=50, null=True)),
                ('ubicacion_anuncio', models.CharField(max_length=50, null=True)),
                ('edad_min', models.IntegerField(null=True)),
                ('edad_max', models.IntegerField(null=True)),
                ('genero', models.CharField(choices=[('todos', 'Todos'), ('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=20, null=True)),
                ('ubicacion', models.CharField(max_length=200, null=True)),
                ('intereses', models.TextField(null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('impresiones', models.IntegerField(default=0)),
                ('clics', models.IntegerField(default=0)),
                ('conversiones', models.IntegerField(default=0)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('campania_facebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_facebook', to='campannias.campanafacebook')),
                ('campania_google', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_google', to='campannias.campanagoogle')),
                ('campania_instagram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_instagram', to='campannias.campanainstagram')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
