# Generated by Django 5.1.6 on 2025-05-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campannias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanainstagram',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20),
        ),
    ]
