# Generated by Django 5.2 on 2025-05-18 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campannias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('edad_min', models.IntegerField(blank=True, null=True)),
                ('edad_max', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('intereses', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('impresiones', models.IntegerField(default=0)),
                ('clics', models.IntegerField(default=0)),
                ('conversiones', models.IntegerField(default=0)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='campannias.campania')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Segmentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_edad_min', models.IntegerField()),
                ('rango_edad_max', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('intereses', models.TextField(help_text='Intereses separados por comas')),
                ('nivel_educativo', models.CharField(max_length=100)),
                ('experiencia_minima', models.IntegerField(help_text='Años de experiencia mínima')),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentaciones', to='campannias.campania')),
            ],
        ),
        migrations.DeleteModel(
            name='CredencialAPI_google',
        ),
    ]
