# Generated by Django 5.2 on 2025-05-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campannias', '0002_campanainstagram_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanafacebook',
            name='url_redireccion',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campanainstagram',
            name='url_redireccion',
            field=models.URLField(blank=True, null=True),
        ),
    ]
