# Generated by Django 5.2 on 2025-05-18 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campannias', '0002_campania_resultadocampania_segmentacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadocampania',
            name='campania',
        ),
        migrations.RemoveField(
            model_name='segmentacion',
            name='campania',
        ),
        migrations.CreateModel(
            name='CampaniaFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_anuncio', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('carousel', 'Carousel'), ('coleccion', 'Colección')], max_length=50)),
                ('formato_anuncio', models.CharField(max_length=50)),
                ('ubicacion_anuncio', models.CharField(max_length=50)),
                ('segmentacion_edad_min', models.IntegerField()),
                ('segmentacion_edad_max', models.IntegerField()),
                ('segmentacion_genero', models.CharField(max_length=20)),
                ('segmentacion_ubicacion', models.CharField(max_length=200)),
                ('segmentacion_intereses', models.TextField()),
                ('idioma', models.CharField(max_length=50)),
                ('dispositivo', models.CharField(max_length=50)),
                ('comportamiento', models.TextField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resultadocampania',
            name='campania_facebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_facebook', to='campannias.campaniafacebook'),
        ),
        migrations.CreateModel(
            name='CampaniaGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_campana', models.CharField(choices=[('busqueda', 'Búsqueda'), ('display', 'Display'), ('video', 'Video'), ('shopping', 'Shopping')], max_length=50)),
                ('red_anuncios', models.CharField(max_length=50)),
                ('segmentacion_edad_min', models.IntegerField()),
                ('segmentacion_edad_max', models.IntegerField()),
                ('segmentacion_genero', models.CharField(max_length=20)),
                ('segmentacion_ubicacion', models.CharField(max_length=200)),
                ('segmentacion_intereses', models.TextField()),
                ('palabras_clave', models.TextField()),
                ('presupuesto_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puja_maxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resultadocampania',
            name='campania_google',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_google', to='campannias.campaniagoogle'),
        ),
        migrations.CreateModel(
            name='CampaniaInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_contenido', models.CharField(choices=[('historia', 'Historia'), ('post', 'Post'), ('reels', 'Reels'), ('carousel', 'Carousel')], max_length=50)),
                ('formato_anuncio', models.CharField(max_length=50)),
                ('ubicacion_anuncio', models.CharField(max_length=50)),
                ('segmentacion_edad_min', models.IntegerField()),
                ('segmentacion_edad_max', models.IntegerField()),
                ('segmentacion_genero', models.CharField(max_length=20)),
                ('segmentacion_ubicacion', models.CharField(max_length=200)),
                ('segmentacion_intereses', models.TextField()),
                ('hashtags', models.TextField()),
                ('estilo_visual', models.CharField(max_length=50)),
                ('tono_mensaje', models.CharField(max_length=50)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resultadocampania',
            name='campania_instagram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_instagram', to='campannias.campaniainstagram'),
        ),
        migrations.DeleteModel(
            name='Campania',
        ),
        migrations.DeleteModel(
            name='Segmentacion',
        ),
    ]
