# Generated by Django 5.1.6 on 2025-05-20 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campannias', '0003_remove_resultadocampania_campania_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(max_length=255)),
                ('tipo_presupuesto', models.CharField(choices=[('daily_budget', 'Presupuesto Diario'), ('lifetime_budget', 'Presupuesto Total')], max_length=20)),
                ('monto_presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento_cobro', models.CharField(choices=[('IMPRESSIONS', 'Impresiones'), ('CLICKS', 'Clics'), ('LINK_CLICKS', 'Clics en Enlaces'), ('VIDEO_VIEWS', 'Vistas de Video')], max_length=20)),
                ('objetivo_optimizacion', models.CharField(choices=[('LINK_CLICKS', 'Clics en Enlaces'), ('REACH', 'Alcance'), ('IMPRESSIONS', 'Impresiones'), ('VIDEO_VIEWS', 'Vistas de Video'), ('POST_ENGAGEMENT', 'Interacción con Publicaciones')], max_length=20)),
                ('edad_min', models.IntegerField()),
                ('edad_max', models.IntegerField()),
                ('genero', models.CharField(choices=[('ALL', 'Todos'), ('MALE', 'Masculino'), ('FEMALE', 'Femenino')], max_length=10)),
                ('ubicaciones', models.TextField()),
                ('intereses', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada')], default='PAUSED', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña Facebook',
                'verbose_name_plural': 'Campañas Facebook',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
