# Generated by Django 5.1.6 on 2025-05-20 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campannias', '0004_campanafacebook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text='ID de cliente de Google Ads', max_length=255)),
                ('developer_token', models.CharField(help_text='Developer Token de Google Ads', max_length=255)),
                ('refresh_token', models.CharField(help_text='Refresh Token de OAuth 2.0', max_length=255)),
                ('access_token', models.CharField(help_text='Access Token de OAuth 2.0', max_length=255)),
                ('mcc_account', models.BooleanField(default=False, help_text='Indica si es una cuenta MCC')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_campana', models.CharField(choices=[('SEARCH', 'Búsqueda'), ('DISPLAY', 'Display'), ('VIDEO', 'Video'), ('SHOPPING', 'Shopping')], max_length=20)),
                ('presupuesto_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('palabras_clave', models.TextField(help_text='Palabras clave separadas por comas')),
                ('ubicaciones', models.TextField(help_text='Ubicaciones objetivo separadas por comas')),
                ('idiomas', models.TextField(help_text='Idiomas objetivo separados por comas')),
                ('puja_maxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estrategia_puja', models.CharField(choices=[('MANUAL_CPC', 'CPC Manual'), ('MAXIMIZE_CONVERSIONS', 'Maximizar Conversiones'), ('TARGET_CPA', 'CPA Objetivo'), ('TARGET_ROAS', 'ROAS Objetivo')], max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada')], default='PAUSED', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña Google',
                'verbose_name_plural': 'Campañas Google',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
