# Generated by Django 5.1.6 on 2025-05-22 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campannias', '0005_campanagoogle'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanafacebook',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='campanafacebook',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='campanafacebook',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='campanafacebook',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='campanagoogle',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='campanagoogle',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='campaniafacebook',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='campaniafacebook',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='campaniagoogle',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='campaniagoogle',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='campaniainstagram',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='campaniainstagram',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='campanagoogle',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='campanagoogle',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
